### PR TITLE
Added LetMeIn to links, added meeting times for Devcade and ImagineRIT to sidebar

### PR DESCRIPTION
**Pull request by ES542**
Easy access to LetMeIn, in case someone locks themself out of the building

Also added Devcade and ImagineRIT meeting times to the sidebar (don't know why this commit was added here but I don't know how to separate them)

### CODE REVIEW

**Review by mxmeinhold — APPROVED** [review]
Looks good to me, though could you paste a screenshot of what "material:notification" looks like?

**Comment by ES542** [comment]
this is what it looks like

thing

**Comment by mxmeinhold** [comment]
Awesome! @jabbate19 are you able to merge and deploy this

**Review by jabbate19 — APPROVED** [review]
LGTM!

**Pull request merged**
